#!/bin/bash

# ci_pre_xcodebuild.sh
# This script runs in Xcode Cloud right before the build starts.
# It generates the Secrets.xcconfig file from environment variables provided by Xcode Cloud.

set -e

echo "=========================================="
echo "Creating Secrets.xcconfig file..."
echo "=========================================="

# CI_WORKSPACE is an environment variable provided by Xcode Cloud pointing to the project root
CONFIG_FILE_PATH="$CI_WORKSPACE/TechQTA/Config/Secrets.xcconfig"

# Validate required environment variables
if [ -z "$CLOUDFLARE_ACCOUNT_ID" ]; then
    echo "ERROR: CLOUDFLARE_ACCOUNT_ID environment variable is not set."
    exit 1
fi

if [ -z "$CLOUDFLARE_API_KEY" ]; then
    echo "ERROR: CLOUDFLARE_API_KEY environment variable is not set."
    exit 1
fi

# Write the secrets into the .xcconfig file
echo "# Cloudflare API Configuration (Generated by Xcode Cloud)" > $CONFIG_FILE_PATH
echo "CLOUDFLARE_ACCOUNT_ID = ${CLOUDFLARE_ACCOUNT_ID}" >> $CONFIG_FILE_PATH
echo "CLOUDFLARE_API_KEY = ${CLOUDFLARE_API_KEY}" >> $CONFIG_FILE_PATH

echo "=========================================="
echo "✓ Secrets.xcconfig created successfully at: $CONFIG_FILE_PATH"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Update TechQTA/Config/CloudflareSecrets.example.plist with correct key names"
echo "2. Configure Xcode Cloud environment variables in App Store Connect"
