#!/bin/bash

# ci_pre_xcodebuild.sh
# This script runs in Xcode Cloud right before the build starts.
# It generates the Secrets.xcconfig file from environment variables provided by Xcode Cloud.

set -e

echo "=========================================="
echo "Creating Secrets.xcconfig file..."
echo "=========================================="

# CI_PRIMARY_REPOSITORY_PATH is the Xcode Cloud env var for the repo root (e.g. /Volumes/workspace/repository)
# CI_WORKSPACE was deprecated/removed - use CI_PRIMARY_REPOSITORY_PATH instead
REPO_ROOT="${CI_PRIMARY_REPOSITORY_PATH:-$(cd "$(dirname "$0")/.." && pwd)}"
CONFIG_DIR="$REPO_ROOT/TechQTA/Config"
CONFIG_FILE_PATH="$CONFIG_DIR/Secrets.xcconfig"

# Ensure Config directory exists
mkdir -p "$CONFIG_DIR"

# Validate required environment variables
if [ -z "$CLOUDFLARE_ACCOUNT_ID" ]; then
    echo "ERROR: CLOUDFLARE_ACCOUNT_ID environment variable is not set."
    exit 1
fi

if [ -z "$CLOUDFLARE_API_KEY" ]; then
    echo "ERROR: CLOUDFLARE_API_KEY environment variable is not set."
    exit 1
fi

# Write the secrets into the .xcconfig file
echo "# Cloudflare API Configuration (Generated by Xcode Cloud)" > "$CONFIG_FILE_PATH"
echo "CLOUDFLARE_ACCOUNT_ID = ${CLOUDFLARE_ACCOUNT_ID}" >> "$CONFIG_FILE_PATH"
echo "CLOUDFLARE_API_KEY = ${CLOUDFLARE_API_KEY}" >> "$CONFIG_FILE_PATH"

echo "=========================================="
echo "✓ Secrets.xcconfig created successfully at: $CONFIG_FILE_PATH"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Update TechQTA/Config/CloudflareSecrets.example.plist with correct key names"
echo "2. Configure Xcode Cloud environment variables in App Store Connect"
